CREATE TABLE animals(
    id int GENERATED BY DEFAULT AS IDENTITY ,
    name VARCHAR NOT NULL,
    date_of_birth date  NOT NULL ,
    escape_attempts int NOT NULL,
    neutered bit NOT NULL,
    weight_kg decimal(10,2) NOT NULL
);
-- Add new column species
ALTER TABLE animals ADD species VARCHAR (255);

-- Create new table owners
CREATE TABLE owners(id SERIAL PRIMARY KEY,full_name VARCHAR NOT NULL,age INT NOT NULL);

-- Create new table species
CREATE TABLE species(id SERIAL PRIMARY KEY, name VARCHAR NOT NULL);

-- Drop species column in animal table
ALTER TABLE animals DROP species;

-- Add column species_id which is a foreign key referencing species table
ALTER TABLE animals ADD species_id INT;
ALTER TABLE animals ADD CONSTRAINT fk_1 FOREIGN KEY (species_id) REFERENCES species(id);

-- Add column owner_id which is a foreign key referencing owners table
ALTER TABLE animals ADD owner_id INT;
ALTER TABLE animals ADD CONSTRAINT fk_2 FOREIGN KEY (owner_id) REFERENCES owners (id);
    
-- Create a table named vets with (id,name,age) columns:
CREATE TABLE vets (id SERIAL PRIMARY KEY , name VARCHAR NOT NULL,age INT NOT NULL,date_of_graduation DATE NOT NULL);

-- many-to-many relationship between the tables species and vets
CREATE TABLE specializations (vet_id INT NOT NULL, species_id INT NOT NULL, CONSTRAINT fk_vet FOREIGN KEY (vet_id) REFERENCES vets(id),CONSTRAINT fk_species FOREIGN KEY(species_id) REFERENCES species(id));

--many-to-many relationship between the tables animals and vets
CREATE TABLE visits(vets_id INT NOT NULL, animals_id INT NOT NULL , visit_date DATE NOT NULL, CONSTRAINT fk_vets FOREIGN KEY(vets_id) REFERENCES vets(id) , CONSTRAINT fk_animals FOREIGN KEY(animals_id) REFERENCES animals(id));


-- create index for visit -animal_id column
CREATE INDEX idx_animal_id ON visits (animal_id);
-- create index for visit vet_id column
CREATE INDEX idx_vet_id ON visits (vet_id);
-- create index for owners email column
CREATE INDEX  idx_email ON owners(email);